---
- hosts: 10.30.0.58
  gather_facts: false
  become_user: root
  vars_files:
    - ./group_vars/vars
  tasks:
    - name: Get worker token
      include_vars:
        file: /tmp/worker_token
        name: add_worker
    - name: Add Worker nodes to the swarm
      command: "{{ add_worker.token }}"
