---
- hosts: 10.30.0.58
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ./group_vars/vars
  tasks:
    - name: get worker token
      include_vars:
        file: /tmp/workertoken
        name: add_worker
    - name: add worker node to the swarm
      command: "docker swarm join --token {{ add_worker  }}"
