---
- hosts: UCP-worker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ./group_vars/vars
  tasks:
    - name: get worker token
      include_vars:
        file: /tmp/worker_token
        name: add_worker
    - name: add worker node to the swarm
      command: "{{ add_worker  }}"
