---
- hosts: DTR-manager
  gather_facts: false
  become_user: root
  vars_files:
    - ../group_vars/vars
  tasks:
    - name: Get worker token
      include_vars:
        file: /tmp/worker_token
        name: add_worker
    - name: Add Worker nodes to the swarm
      command: "{{ add_worker.token }}"

    - name: download and install DTR
      shell:
        docker run -t --rm  docker/dtr:{{ DTR_Version }} install --ucp-node {{ DTR_Hostname }} --ucp-insecure-tls --ucp-password {{ UCP_Admin_Pass }} --ucp-url {{ UCP_URL }} --ucp-username {{ UCP_Admin }}
